# Netlify deploy configuration
# See https://www.netlify.com/docs/continuous-deployment/#deploy-contexts

# Global settings applied to the whole site.
#
# “publish” is the directory to publish (relative to root of your repo),
# “command” is your build command,
# “base” is directory to change to before starting build. if you set base:
#    that is where we will look for package.json/.nvmrc/etc not repo root!

[build]
  publish = "site-build"
  command = "npm run generate-site"

[[redirects]]
  from = "/versions/:majorversion/*"
  to = "https://:majorversion--clever-morse-e60990.netlify.com/:splat"
  status = 200

[[redirects]]
  from = "/unexpected-*"
  to = "https://unexpectedjs.github.io/unexpected-:splat"
  status = 200
